apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-newrelic-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: api
          env:
            - name: NODE_ENV
              value: uat
            - name: NEW_RELIC_APP_NAME
              value: NestJS-Demo-UAT
            - name: NEW_RELIC_LOG_LEVEL
              value: warn
