apiVersion: v1
kind: Service
metadata:
  name: nestjs-newrelic-demo
  namespace: default
  labels:
    app: nestjs-newrelic-demo
spec:
  type: ClusterIP
  selector:
    app: nestjs-newrelic-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestjs-newrelic-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nestjs-newrelic-demo
                port:
                  number: 80
